name: Deploy

on:
  repository_dispatch:
    types:
      - deploy

  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/neswear-deploy
            if [ "${{ github.event.inputs.environment }}" = "prod" ]; then
              cp .env.prod.example .env
            elif [ "${{ github.event.inputs.environment }}" = "staging" ]; then
              cp .env.staging.example .env
            else
              cp .env.dev.example .env
            fi
            git pull
            docker compose pull
            docker compose up -d 
            docker compose exec -T backend npm run seed
